### ISSUE TITLE
How to build that? :O

### ISSUE THREAD

**Issue by TheOldRustyCrown** [fallahn/crogine#105]
```
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CROGINE (missing: CROGINE_LIBRARIES CROGINE_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  samples/cmake/modules/FindCROGINE.cmake:10 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  samples/golf/CMakeLists.txt:59 (find_package)
```
  
Unbuildable at all :|

Is there any magic combination to run it? I’m a beginner, I haven’t yet worked 90 years in production with the C language, so the build instructions are like : "well, here’s a source, you know what to do..." - it’s a little bet short

I also tried to build it by Visual Studio 2022 and there is no one binary file at all, only .obj files everywhere :| 
I also tried to go to a local fortune teller, a shaman and a monastery, but their wisdom did not help me understand your idea

**Comment by fallahn** [comment]
Before you can build any of the projects in the samples directory, you need to build and install the crogine library from the root directory. On linux from scratch it's something like:

```
mkdir ~/repos && cd ~/repos
git clone https://github.com/fallahn/crogine

...

cd crogine && mkdir build && cd build
cmake .. -DUSE_GL41=true

sudo make -j install
```

This installs the library to `/usr/local/lib` by default, and the cmake file for the sample project will know where to find it.

On windows this doesn't quite work because windows doesn't have a default library directory. You can supply one when configuring cmake:

    cmake .. -DUSE_GL41=true -DCMAKE_INSTALL_PREFIX="c:/some/path/to/install/to"

which will make cmake install the crogine library to that directory after it's built.

Then when you configure cmake for the sample project (in this case golf) you have to tell cmake where to find the crogine library

    cmake -DCMAKE_PREFIX_PATH="c:/some/path/to/install/to"

Generally it's easier to use the Visual Studio solution file on windows, which is already pre-configured for all the libraries/projects in t he repository. The files are output to `crogine/x64/Debug` or `crogine/x64/Release`

If you want to build on mac there's a guide included in the repository here: https://github.com/fallahn/crogine/blob/master/samples/golf/macOS/macOS.md

**Comment by TheOldRustyCrown** [comment]
I tried Visual Studio, but it only creates a lot of OBJ files, but no one binary, seems I have no chance to install it, your first method also doesn't working for me :|

**Comment by fallahn** [comment]
Can I ask why you're trying to build the game from source? If you just want to play it you can find it on itch.io: https://fallahn.itch.io/super-video-golf or Steam: https://store.steampowered.com/app/2173760/Super_Video_Golf/ - and there's a sale starting on Monday if you want a discount.

**Comment by TheOldRustyCrown** [comment]
I just tried to test the new engine :|

**Comment by fallahn** [comment]
I'm a little confused. This is my personal project which I use mostly to make Super Video Golf, and to experiment with game development. It's shared here in case anyone else might find it useful, and because a lot of what I learn comes from the projects other people have shared.

I'm happy if you want to use it to learn, or for one of your projects, and if you have a specific question about something I'll do my best to answer it. However it's not a 'new engine' or anything - just check the source and you'll see some of it even dates back to 2017. I'm not sure what the 'old' engine would be, other than perhaps one of my other projects [xygine](https://github.com/fallahn/xygine).

However if, like you say, you've not worked 90 years in production with C, then this project is likely not for you. Try something like SFML - I learned a lot from the library (and met some really nice folks too!) and perhaps get a couple of books which explain C/C++ and game development far better than I ever could. I particularly recommend [Game Programming Patterns](https://gameprogrammingpatterns.com/contents.html) by Robert Nystrom and [SFML Game Development](https://www.packtpub.com/product/sfml-game-development/9781849696845). Reading these and practicing with SFML is what inspired me to make my own projects.

**Comment by TheOldRustyCrown** [comment]
Okay, thank you! ;)
