### ISSUE TITLE
Putting in ball leads to freeze (integer overflow)

### ISSUE THREAD

**Issue by wklumpen** [fallahn/crogine#43]
Client of a network game sunk a putt and we ended up with this:
![golf_game_issue](https://user-images.githubusercontent.com/7478016/141888603-149e79e9-9726-408b-9856-8d03826ff461.png)
:

Looks like an integer overflow?

**Comment by fallahn** [comment]
Hi, thanks for the feedback! I've narrowed this down to a NaN appearing in the ball's transform somewhere server-side, however it happens so rarely (last night it happened to me for the first time in 2 weeks...) that it's been difficult to reproduce reliably and debug. Now that I know that it's a NaN I can start to zero in on what I think might be either a div0 or a sqrt of a negative number, so hopefully I can get it fixed in time for the next update. If you're feeling adventurous to can check out the progress in the `golf_physics` branch 👍
