### ISSUE TITLE
SDL headers are leaked

### ISSUE THREAD

**Issue by JonnyPtn** [fallahn/crogine#97]
Noticed this while updating the golf cmake to use modern target-based include directories - `Types.hpp` includes SDL headers, so any project using crogine will also need the SDL include paths set up.

Perhaps some forward declarations or using a pimpl would mean we can avoid this requirement and "hide" the SDL implementation from crogine users

**Comment by fallahn** [comment]
Unfortunately SDL is leaked throughout the entire library. For instance the events passed down through projects are all pure SDL events so they'll always need the SDL headers anyway. I've abstracted some of the enums/api (eg the `GameController` stuff - though mostly because SDL's game controller interface is confusing as all balls) but it boiled down to it just being me who uses crogine, and I can put up with some direct SDL usage - especially if abstraction risks adding some unnecessary overhead 🙂

If, in the unlikely event, crogine explodes in popularity it might be worth working on, but for now I'm happy to leave it as-is.

**Comment by JonnyPtn** [comment]
Makes sense, just wanted to flag it in case. Will close this for now but can reopen later if desired
